/* vitapoke: a compile and link check over the DS SDK surface the Vita platform layer implements.
 *
 * Nothing here runs. tests/vita/run.sh only checks that it builds, which is what catches a psp2
 * rename, a libntr signature change, or a DS interface the port stopped providing -- before a full
 * build spends twenty minutes finding out.
 *
 * Every call below is one the game or libntr makes. Keep them in step: a DS interface that port/vita
 * starts implementing belongs here too.
 *
 * The DS hardware registers (s_HW_MAIN_MEM, s_reg_PAD_KEYINPUT and the rest) are generated by the real
 * build from the decompilation, so they are defined here instead. That is the one thing this check
 * cannot verify for itself; it is checking the code, not the register layout.
 */
#include <stdlib.h>
#include <stdio.h>
#include <string.h>

#include <nitro.h>

#include "../../port/vita/include/vita_os.h"
#include "../../port/vita/include/vita_input.h"

/* ---------------------------------------------------------------- stand-ins for the real build
 *
 * Definitions the application and the generated register backing supply. Sized and named to match, so
 * the link exercises the same symbols.
 */
u8 s_HW_MAIN_MEM[0x800000];
u8 s_HW_MAIN_MEM_SYSTEM[HW_MAIN_MEM_SYSTEM_SIZE];   /* HW_BUTTON_XY_BUF lives in here */
REGType16v s_reg_PAD_KEYINPUT;
u32 s_HW_INTR_CHECK_BUF;
REGType32v s_reg_OS_IF;

/* The DS's cartridge lock word, which the real build's register backing provides. */
u8 s_HW_MAIN_MEM_SHARED[HW_MAIN_MEM_SHARED_SIZE];

/* The sound engine's switch, which the DS mixer defines in the real build. */
int VitaNativeSoundSilent = 1;

/* The renderer's, which this check does not link. */
unsigned VitaNativeRenderFrameCount(void) { return 0; }

/* What the platform layer offers the application. These live in port/vita and are declared where
 * their users are, so they are declared here too rather than pulling the application in. */
void VitaNativeVBlankReset(void);
unsigned long long VitaNativeVBlankIdleTake(void);
unsigned VitaNativeVBlankWaitsTake(void);
void VitaNativeVBlankFrameComplete(void);
void VitaNativeStackProbeInit(void);
unsigned VitaNativeStackHighWater(unsigned *total);
void VitaNativeMemReport(const char *tag);
void VitaNativeMemPoll(void);
int VitaNativeAudioOutReady(void);
unsigned VitaNativeAudioOutFill(void);
unsigned VitaNativeAudioOutTargetFill(void);
unsigned VitaNativeAudioOutCapacity(void);
void VitaNativeAudioOutWrite(const short *interleaved, unsigned frames);
void VitaNativeAudioOutStats(unsigned *fill, unsigned *underruns, unsigned *dropped, unsigned *written);
void VitaNativeAudioOutShutdown(void);

static void ThreadBody(void *arg) { (void)arg; }
static void AlarmHandler(void *arg) { (void)arg; }
static void RtcDone(RTCResult result, void *arg) { (void)result; (void)arg; }

int main(void)
{
	/* ------------------------------------------------ os_core.c: arena, tick, interrupts */
	OS_Init();
	OS_InitTick();
	if (!OS_IsTickAvailable())
		return 1;
	{
		OSTick tick = OS_GetTick();
		OS_SetTick(tick);
		(void)OS_GetTickLo();
	}
	{
		void *lo = OS_AllocFromArenaLo(OS_ARENA_MAIN, 64, 32);
		void *hi = OS_AllocFromArenaHi(OS_ARENA_MAIN, 64, 32);
		OS_SetArenaLo(OS_ARENA_MAIN, lo);
		OS_SetArenaHi(OS_ARENA_MAIN, hi);
		(void)OS_GetInitArenaLo(OS_ARENA_MAIN);
		(void)OS_GetInitArenaHi(OS_ARENA_MAIN);
	}
	{
		OSIntrMode mode = OS_DisableInterrupts();
		OS_RestoreInterrupts(mode);
		(void)OS_GetProcMode();
		OS_SetIrqFunction(OS_IE_V_BLANK, NULL);
		OS_EnableIrqMask(OS_IE_V_BLANK);
		OS_DisableIrqMask(OS_IE_V_BLANK);
		OS_SetIrqMask(OS_IE_V_BLANK);
		OS_ResetRequestIrqMask(OS_IE_V_BLANK);
		(void)OS_GetIrqFunction(OS_IE_V_BLANK);
	}
	{
		u32 entropy[8];
		OS_GetLowEntropyData(entropy);
	}
	SVC_WaitByLoop(1);
	CARD_SetCacheFlushThreshold(0, 0);

	/* ------------------------------------------------ the DS execution lock */
	VitaOS_Enter();
	if (!VitaOS_Held())
		return 1;
	{
		unsigned depth = VitaOS_Release();
		VitaOS_Reacquire(depth);
	}
	VitaOS_TableLock();
	VitaOS_TableUnlock();
	(void)VitaOS_Now();
	VitaOS_Leave();

	/* ------------------------------------------------ os_thread.c */
	OS_InitThread();
	if (!OS_IsThreadAvailable())
		return 1;
	{
		static OSThread thread;
		static u8 stack[4096];
		static OSThreadQueue queue;

		OS_InitThreadQueue(&queue);
		OS_CreateThread(&thread, ThreadBody, NULL, stack + sizeof stack, sizeof stack, 16);
		OS_SetThreadDestructor(&thread, NULL);
		(void)OS_GetThreadDestructor(&thread);
		OS_SetThreadParameter(&thread, NULL);
		(void)OS_GetThreadParameter(&thread);
		(void)OS_GetThreadPriority(&thread);
		OS_SetThreadPriority(&thread, 17);
		(void)OS_IsThreadInList(&thread);
		(void)OS_IsThreadTerminated(&thread);
		(void)OS_GetThread(0);
		(void)OS_GetNumberOfThread();
		(void)WIN_OS_GetCurrentThread();
		OS_WakeupThreadDirect(&thread);
		OS_WakeupThread(&queue);
		OS_JoinThread(&thread);
		OS_YieldThread();
		OS_RescheduleThread();
		OS_Sleep(0);
		{
			u32 depth = OS_DisableScheduler();
			OS_EnableScheduler();
			(void)depth;
		}
	}

	/* ------------------------------------------------ os_alarm.c */
	OS_InitAlarm();
	if (!OS_IsAlarmAvailable())
		return 1;
	{
		static OSAlarm alarm, periodic;
		OS_CreateAlarm(&alarm);
		OS_SetAlarm(&alarm, 1000, AlarmHandler, NULL);
		OS_SetAlarmTag(&alarm, 1);
		OS_CancelAlarm(&alarm);
		OS_CreateAlarm(&periodic);
		OS_SetPeriodicAlarm(&periodic, OS_GetTick(), 1000, AlarmHandler, NULL);
		OS_CancelAlarms(1);
		OS_CancelAllAlarms();
	}
	(void)VitaNativeAlarmInCallback();
	OS_EndAlarm();

	/* ------------------------------------------------ input.c: pad, touch, clock */
	TP_Init();
	{
		TPData raw, calibrated;
		TPCalibrateParam param;
		static TPData ring[4];

		TP_GetUserInfo(&param);
		TP_SetCalibrateParam(&param);
		TP_RequestSamplingAsync();
		TP_WaitRawResult(&raw);
		TP_GetCalibratedPoint(&calibrated, &raw);
		TP_RequestAutoSamplingStartAsync(0, 1, ring, 4);
		(void)TP_GetLatestIndexInAuto();
		TP_GetLatestRawPointInAuto(&raw);
		TP_WaitBusy(TP_REQUEST_COMMAND_FLAG_AUTO_ON);
		(void)TP_CheckError(TP_REQUEST_COMMAND_FLAG_AUTO_ON);
		TP_RequestAutoSamplingStopAsync();
	}
	RTC_Init();
	{
		RTCDate date;
		RTCTime time;
		RTC_GetDateTime(&date, &time);
		RTC_GetDate(&date);
		RTC_GetTime(&time);
		RTC_GetDateTimeAsync(&date, &time, RtcDone, NULL);
	}
	{
		unsigned keys;
		int down, x, y;
		VitaNativeInputPoll();
		VitaNativeInputVBlank();
		VitaNativeInputGetRenderState(&keys, &down, &x, &y);
		(void)VitaNativeRTCReadCount();
	}

	/* Message queues and mutexes: the DS primitives the sound engine and the game use between
	 * threads, and the cache maintenance the DS needed before its hardware read memory. */
	{
		OSMessageQueue queue;
		OSMessage slots[4], message;
		OSMutex mutex;

		OS_InitMessageQueue(&queue, slots, 4);
		(void)OS_SendMessage(&queue, (OSMessage)0, OS_MESSAGE_NOBLOCK);
		(void)OS_JamMessage(&queue, (OSMessage)0, OS_MESSAGE_NOBLOCK);
		(void)OS_ReadMessage(&queue, &message, OS_MESSAGE_NOBLOCK);
		(void)OS_ReceiveMessage(&queue, &message, OS_MESSAGE_NOBLOCK);
		OS_InitMutex(&mutex);
		(void)OS_TryLockMutex(&mutex);
		OS_UnlockMutex(&mutex);
		OS_LockMutex(&mutex);
		OS_UnlockMutex(&mutex);
		DC_FlushRange(slots, sizeof slots);
		DC_StoreRange(slots, sizeof slots);
		DC_InvalidateRange(slots, sizeof slots);
		DC_FlushAll();
		DC_WaitWriteBufferEmpty();
		(void)OS_IsRunOnEmulator();
		OS_SpinWait(1);
	}

	/* The firmware profile and the cartridge arbitration. */
	{
		OSOwnerInfo owner;
		u8 mac[6];
		s32 id;

		OS_GetOwnerInfo(&owner);
		(void)OS_GetOwnerRtcOffset();
		OS_GetMacAddress(mac);
		id = OS_GetLockID();
		if (id > 0) {
			(void)OS_TryLockCartridge((u16)id);
			(void)OS_UnlockCartridge((u16)id);
			(void)OS_UnLockCartridge((u16)id);
			OS_ReleaseLockID((u16)id);
		}
	}

	/* The save memory. Nothing is opened, so every request answers "no response". */
	{
		(void)CARD_IdentifyBackup(CARD_BACKUP_TYPE_FLASH_4MBITS);
		(void)CARD_GetBackupTotalSize();
		(void)CARD_GetBackupSectorSize();
		(void)CARD_GetBackupPageSize();
		(void)CARD_GetResultCode();
		(void)CARD_TryWaitBackupAsync();
		(void)CARD_WaitBackupAsync();
		CARD_CancelBackupAsync();
		(void)CARDi_RequestStreamCommand(0, 0, 0, NULL, NULL, FALSE, CARD_REQ_READ_BACKUP,
		                                 0, CARD_REQUEST_MODE_RECV);
	}

	/* The vertical blank, the log and what the frame driver reads from them. */
	{
		VitaNativeVBlankReset();
		(void)VitaNativeVBlankIdleTake();
		(void)VitaNativeVBlankWaitsTake();
		VitaNativeVBlankFrameComplete();
		VitaNativeStackProbeInit();
		{
			unsigned total;
			(void)VitaNativeStackHighWater(&total);
		}
		VitaNativeMemReport("checks");
		VitaNativeMemPoll();
	}

	/* The audio output. Opening the port is the one thing that needs hardware, so it is not called;
	 * everything the sound engine asks of it around that is. */
	{
		unsigned fill, under, dropped, written;

		(void)VitaNativeAudioOutReady();
		(void)VitaNativeAudioOutFill();
		(void)VitaNativeAudioOutTargetFill();
		(void)VitaNativeAudioOutCapacity();
		VitaNativeAudioOutWrite(NULL, 0);
		VitaNativeAudioOutStats(&fill, &under, &dropped, &written);
		VitaNativeAudioOutShutdown();
	}

	return 0;
}
